### ISSUE TITLE
[HW_Spreadsheet] change the chart before it exists

### ISSUE THREAD

**Issue by chunhan1928** [gokudera3306/SoftwareEngineeringPractice#2]
也是單純在惡搞input，在 chart 不存在時就加入 data
1. 我覺得在 chart 不存在的情形下，應該要把 command 擋掉
2. 雖然 chart 不存在，輸出會有 `noneExistChart change data n`，但不存在的 chart 不應該能改變任何東西
3. 雖然 chart 不存在，但是依舊可以加入 data，好像有點不合理
input
```
change PieChart A 2
data B 7
addChart PieChart
change PieChart B 5
```
output
```
PieChart change A 2.
PieChart change B 5.
A 28.6%
B 71.4%
```

**Comment by chunhan1928** [comment]
當然，我也可以用不存在的chart去改東西，但是利用其他chart來顯示
例如：PieChart 不存在，但 SpreadSheet 存在
input
```
change PieChart A 2
data B 7
addChart Spreadsheet
change PieChart B 5
```
output
```
PieChart change A 2.
PieChart change B 5.
A 2
B 5
```

**Comment by gokudera3306** [comment]
我認為沒有 chart 確實不該觸發指令，這部分我處理一下

**Comment by gokudera3306** [comment]
已修正在 ad64827343887f5c9abf9d95d9184b0c4475d8b7
